### ISSUE TITLE
Is there the "traj_server package" in the source code?

### ISSUE THREAD

**Issue by GChasing** [ZJU-FAST-Lab/Fast-Perching#1]
Hello, after git clone the source code and "catkin_make" it successfully, I lanch the perching.launch as introduced. But some issues come out as follows:
![Screenshot from 2022-08-09 10-04-45](https://user-images.githubusercontent.com/60912708/183548196-cde74f11-6d7c-4706-a8d1-909c913c1af7.png)
https://github.com/ZJU-FAST-Lab/Fast-Perching/blob/47c9929b4e0767ca3033c441f637483081a82f83/src/planning/launch/perching.launch#L80

Thus, am i doing something wrong or the "traj_server" package lost?

Thank you in advance and hope your reply!

**Comment by GaaiLam** [comment]
> Hello, after git clone the source code and "catkin_make" it successfully, I lanch the perching.launch as introduced. But some issues come out as follows: ![Screenshot from 2022-08-09 10-04-45](https://user-images.githubusercontent.com/60912708/183548196-cde74f11-6d7c-4706-a8d1-909c913c1af7.png)
> 
> https://github.com/ZJU-FAST-Lab/Fast-Perching/blob/47c9929b4e0767ca3033c441f637483081a82f83/src/planning/launch/perching.launch#L80
> 
> Thus, am i doing something wrong or the "traj_server" package lost?
> 
> Thank you in advance and hope your reply!

Hello, sorry for not replying immediately!
I've fixed the problem in the latest commit.
