### ISSUE TITLE
The code differs from the description in the paper

### ISSUE THREAD

**Issue by UAVlover** [ZJU-FAST-Lab/Fast-Perching#2]
Hello , PhD Ji,
     Thanks a lot for your solid work. It helped me a lot. 
      However, there is a confusion for me.  I noticed a slight discrepancy in equation 18(a) in your paper and the corresponding code snippet. In the code, you've used` (robot_l_ - 0.005)` instead of simply `robot_l_`, as it appears in the paper's equation:
`double pen = a_i.dot(pos) - (robot_l_ - 0.005) * a_i.dot(zb) - b_i + robot_r_ * v2_norm;`
In the paper, the equation is defined as:
`double pen = a_i.dot(pos) - robot_l_ * a_i.dot(zb) - b_i + robot_r_ * v2_norm; `
Could you please clarify why (robot_l_ - 0.005) is used in the code ? Thank you. @GaaiLam

**Comment by GaaiLam** [comment]
> Hello , PhD Ji, Thanks a lot for your solid work. It helped me a lot. However, there is a confusion for me. I noticed a slight discrepancy in equation 18(a) in your paper and the corresponding code snippet. In the code, you've used` (robot_l_ - 0.005)` instead of simply `robot_l_`, as it appears in the paper's equation: `double pen = a_i.dot(pos) - (robot_l_ - 0.005) * a_i.dot(zb) - b_i + robot_r_ * v2_norm;` In the paper, the equation is defined as: `double pen = a_i.dot(pos) - robot_l_ * a_i.dot(zb) - b_i + robot_r_ * v2_norm; ` Could you please clarify why (robot_l_ - 0.005) is used in the code ? Thank you. @GaaiLam

Hello, the imu of our drone is 5mm below the plane of the rotors, which means the underside of the drone is (l-0.005)m below the odometry. Thus a small detail does not matter. If your robot_l means the distance between underside and odometry, then you can remove 0.005😂.
